#!/bin/sh
# Rebuild the celnav manual and quick reference PDFs.
# Needs: pandoc, wkhtmltopdf.  Figures are regenerated by build_figs*.py (python3 + cairosvg).
set -e
cd "$(dirname "$0")"
mk() {
  pandoc "$1" -f markdown -t html5 -o /tmp/frag.html
  { echo '<!DOCTYPE html><html><head><meta charset="utf-8"><title>'"$3"'</title><style>'
    cat style.css; echo '</style></head><body>'; cat /tmp/frag.html; echo '</body></html>'
  } > _build.html
  wkhtmltopdf --quiet --enable-local-file-access --page-size A4 \
    --margin-top 16mm --margin-bottom 15mm --margin-left 15mm --margin-right 15mm \
    _build.html "$2"
  rm -f _build.html
}
mk manual.md   ../celnav-manual.pdf   "CELNAV Manual"
mk quickref.md ../celnav-quickref.pdf "CELNAV Quick Reference"
ls -l ../celnav-manual.pdf ../celnav-quickref.pdf
